Look for scripts and reference alignments in fixed locations where no path is provided.

diff --git a/scripts/clonotypeR b/scripts/clonotypeR
--- a/scripts/clonotypeR
+++ b/scripts/clonotypeR
@@ -3,10 +3,41 @@
 set -e
 
 # Path to the reference V and J segments defaults to /etc/clonotyper/references.
-CLONOTYPER_REFERENCE=${CLONOTYPER_REFERENCE:-/etc/clonotyper/references}
+
+if [ -z $CLONOTYPER_REFERENCE ]
+then
+	if [ -d /etc/clonotyper/references ]
+	then
+		CLONOTYPER_REFERENCE=/etc/clonotyper/references
+	else if [ -d /use/share/clonotyper/references ]
+	then
+		CLONOTYPER_REFERENCE=/use/share/clonotyper/references
+	else if [ -d ../references ]
+	then
+		CLONOTYPER_REFERENCE=../references
+	else
+		echo "CLONOTYPER_REFERENCE not set and could not autodetect reference files"
+		exit 1
+			fi
+		fi
+	fi
+fi
 
 # Path to VJsplit defaults to /usr/share/clonotyper.
-CLONOTYPER_SCRIPTS=${CLONOTYPER_SCRIPTS:-/usr/share/clonotyper}
+
+if [ -z $CLONOTYPER_SCRIPTS ]
+then
+	if [ -d /usr/share/clonotyper/scripts ]
+	then
+		CLONOTYPER_SCRIPTS=/usr/share/clonotyper/scripts
+	else if [ -d ../scripts ]
+	then
+		CLONOTYPER_SCRIPTS=../scripts
+	else
+		echo "CLONOTYPER_SCRIPTS not set and could not autodetect path to scripts"
+		fi
+	fi
+fi
 
 # Path to the BAM and temporary files defaults to extraction_files.
 EXTRACT_DIR=${EXTRACT_DIR:-extraction_files}
