Test if $EXTRACT_DIR is present.

diff --git a/scripts/clonotypeR b/scripts/clonotypeR
--- a/scripts/clonotypeR
+++ b/scripts/clonotypeR
@@ -14,11 +14,20 @@ EXTRACT_DIR=${EXTRACT_DIR:-extraction_files}
 # Auto-detect number of threads.
 THREADS=$([ -e /proc/cpuinfo ] && cat /proc/cpuinfo | grep -c processor)
 
+function test_extract_dir {
+	if ! [ -d $EXTRACT_DIR ]
+	then
+	  echo "Error: could not find the directory '$EXTRACT_DIR'. $?"
+	  exit 1
+	fi
+}
+
 case $1 in
 	convert)
 	;;
 	detect)
 		shift
+		test_extract_dir
 		for FASTQ_FILE in "$*"
 		do
 			LIBRARY=$(basename $FASTQ_FILE .fq)
@@ -31,6 +40,7 @@ case $1 in
 	;;
 	extract)
 		shift
+		test_extract_dir
 		for BAM_FILE in "$*"
 		do
 			LIBRARY=$(basename $BAM_FILE .bam)
